name: Autobuild
trigger:
  branches:
    include:
      - master

stages:
  - stage: build
    jobs:
      - job:
        strategy:
          matrix:
            windows:
              name: windows
              imageName: windows-latest
              fileName: cf-downloader.exe
            linux:
              name: linux
              imageName: ubuntu-latest
              fileName: cf-downloader

        pool:
          vmImage: $(imageName)
        steps:
          - script: rustup default nightly && rustup component add clippy
            displayName: select nightly rustc
          - script: cargo clippy --release
            displayName: Run cargo clippy
          - script: cargo build --release
            displayName: Run cargo build
          - script: strip -s $(System.DefaultWorkingDirectory)/target/release/$(fileName)
            condition: ne(variables['Agent.OS'], 'Windows_NT')
            displayName: Strip output file
          - publish: $(System.DefaultWorkingDirectory)/target/release/$(fileName)
            artifact: cf-downloader-$(Agent.OS)-$(Agent.OSArchitecture)
            displayName: cf-downloader-$(Agent.OS)-$(Agent.OSArchitecture)
