[package]
name = "cf-downloader"
version = "0.1.0"
authors = ["aplqo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
