[package]
name = "cf-downloader"
version = "0.1.0"
authors = ["aplqo <aplqo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cf-downloader"
path = "./src/downloader/lib.rs"

[[bin]]
name "cf-downloader"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
regex = "1.4.4"
futures = "0.3.13"